### ISSUE TITLE
mywalet

### ISSUE THREAD

**Issue by Masoodshafiee** [LocalCryptos/LocalCryptosWalletBackupExplorer#42]

**Comment by Paritavana** [comment]
#42

**Comment by Paritavana** [comment]
https://github.com/LocalCryptos/LocalCryptosWalletBackupExplorer/issues/42#issue-2298958039

**Comment by Paritavana** [comment]
https://github.com/LocalCryptos/LocalCryptosWalletBackupExplorer/issues/42#issuecomment-2121490877
